source = ./colors.conf
source = ./hyprconf/monitors.conf
source = ./hyprconf/theme.conf
source = ./hyprconf/autostart.conf
source = ./hyprconf/env.conf
source = ./hyprconf/look_and_feel.conf
source = ./hyprconf/input.conf
source = ./hyprconf/keybinds.conf
source = ./hyprconf/windowrules.conf

###########
# TESTING #
###########

icc = /home/archangel/.config/hypr/icc/FW12Cal.icm
