exec-once = systemctl --user start hyprpolkitagent
exec-once = awww-daemon
exec-once = hyprpanel
exec-once = udiskie
exec-once = hyprsunset
exec-once = easyeffects --gapplication-service
# exec-once = kdeconnectd
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = cliphist wipe
exec-once = thunderbird
exec-once = systemctl --user start opentabletdriver.service

exec-once = ~/.config/hypr/vesktop.sh
exec-once = steam
exec-once = wppr scrape

# Theme
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
# exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"   # for GTK3 apps
