exec-once = hyprpanel
exec-once = dunst
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprsunset
exec-once = awww-daemon
exec-once = udiskie
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = cliphist wipe
exec-once = gnome-keyring-daemon --foreground --components=pkcs11,secrets --control-directory=/run/user/1000/keyring/
exec-once = nm-applet
exec-once = bluetoothctl power off
exec-once = iio-hyprland
exec-once = hypridle
exec-once = wppr scrape
