env = PROTON_DLSS_UPGRADE=1
env = PROTON_DLSS_INDICATOR=1
env = PROTON_NVIDIA_LIBS=1
# env = PROTON_ENABLE_WAYLAND=1
env = PROTON_NO_WM_DECORATION=1
env = PROTON_LOCAL_SHADER_CACHE=0
env = PROTON_ENABLE_MEDIACONV=1

